<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-15T17:22:06 NPT" name="Default suite" finished-at="2022-06-15T17:22:30 NPT" duration-ms="24474">
    <groups>
    </groups>
    <test started-at="2022-06-15T17:22:06 NPT" name="Default test" finished-at="2022-06-15T17:22:30 NPT" duration-ms="24474">
      <class name="com.screenshot.ScreenShootTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb]" started-at="2022-06-15T17:22:06 NPT" name="setup" finished-at="2022-06-15T17:22:17 NPT" duration-ms="11837" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testcase1()[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb]" started-at="2022-06-15T17:22:17 NPT" name="testcase1" finished-at="2022-06-15T17:22:18 NPT" duration-ms="644" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb]" started-at="2022-06-15T17:22:18 NPT" name="teardown" finished-at="2022-06-15T17:22:20 NPT" duration-ms="2282" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testcase1 status=SUCCESS method=ScreenShootTest.testcase1()[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb]" started-at="2022-06-15T17:22:20 NPT" name="setup" finished-at="2022-06-15T17:22:27 NPT" duration-ms="6947" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testcase2()[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb]" started-at="2022-06-15T17:22:27 NPT" name="testcase2" finished-at="2022-06-15T17:22:27 NPT" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.screenshot.ScreenShootTest.testcase2(ScreenShootTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb]" started-at="2022-06-15T17:22:27 NPT" name="teardown" finished-at="2022-06-15T17:22:30 NPT" duration-ms="2688" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testcase2 status=FAILURE method=ScreenShootTest.testcase2()[pri:0, instance:com.screenshot.ScreenShootTest@48f278eb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.screenshot.ScreenShootTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
